### ISSUE TITLE
Audio issues in Linux Release Beta_21_4

### ISSUE THREAD

**Issue by lonewolf19991** [Robosturm/Commander_Wars#746]
Linux compilation of the game yields audio issues.  The following was tested under Fedora 35, 64 bits.

This is how the game was run:

- The game was downloaded from here: https://github.com/Robosturm/Commander_Wars/releases/download/Beta_21_4_Hotfix/Commander_Wars_Ubuntu.zip
- The game was unzipped
- The Qt components were downloaded through this tool: https://www.qt.io/download-open-source 
- Version 6.2.2 of the libraries were installed alongside with the multimedia components of it
- ~/.bashrc was modified to comply with the location of the installed components, in this case export LD_LIBRARY_PATH=/home/username/Qt/6.2.2/gcc_64/lib:$LD_LIBRARY_PATH was added as root at the very bottom of the file
- Logged out and logged back in to make the changes propagate
- After that the executable was run directly from the terminal through ./Commander_Wars 
- When loading any map as single player, and clicking start as shown in the screenshot, the game crashes 

![Screenshot from 2021-12-26 00-44-48](https://user-images.githubusercontent.com/96459683/147401100-5990641d-9da5-45c9-911f-2d54b6fc621a.png)

![Screenshot from 2021-12-26 00-44-53](https://user-images.githubusercontent.com/96459683/147401108-a54404f2-cf35-4bfe-a6fb-903b9ccae5a9.png)

Output of the Terminal when the executable crashes.
![Screenshot from 2021-12-26 00-45-30](https://user-images.githubusercontent.com/96459683/147401110-1789409b-cb5e-47fa-85fc-a1006e0806e3.png)

The game seems to be detecting 2 different audio output sources, when trying to change it the game also crashes, with the following output. 
![Screenshot from 2021-12-26 00-42-46](https://user-images.githubusercontent.com/96459683/147401207-5bce621d-8971-42e9-9d22-7258806e970c.png)

![Screenshot from 2021-12-26 00-59-06](https://user-images.githubusercontent.com/96459683/147401323-7d3797e7-9153-40b6-8371-fa3fb0c09750.png)

I initially thought it had to do with file and folder permissions, so I granted them the highest amount chmod -R 777 Commander_Wars
but the results were the same (Terrible practice, I know, but I wanted to rule that out) 

P.S. If the volume is put to 0, in the settings, the game does not crash and plays normally.
P.S.2 Tried using components of 6.2.1 and the issues were similar in nature, although audio was garbled in such instances and would cut off when certain sounds would play, such as engagement of units. After which there would be no sound on the game again.

**Comment by Robosturm** [comment]
Sounds like an Issue qt needs to fix and not CoW....

**Comment by Robosturm** [comment]
@lonewolf19991 you may try out the current source code i added a none caching version which is the default compile version for the none windows versions, since an similar problem happens with android

**Comment by lonewolf19991** [comment]
> @lonewolf19991 you may try out the current source code i added a none caching version which is the default compile version for the none windows versions, since an similar problem happens with android

I cloned from the master branch, I recompiled with the exact same CMakeLists.txt, except that I made a few changes to make it compile properly, which are:

`set(Qt6_DIR "/home/nameless/Qt/6.2.2/gcc_64/lib/cmake/Qt6")
set(XDG_RUNTIME_DIR "/run/user/1000")
set(XKB_INCLUDE_DIR "/usr/include/xcb")
set(XKB_LIBRARY "/usr/lib/x86_64-linux-gnu/")
set(Vulkan_INCLUDE_DIR "/usr/lib/x86_64-linux-gnu/")
`

These are added to include the dependencies, but the error persisted, it is to note however, that the application takes longer to trigger a gstreamer error, however once it does, the entire application hangs. 

For further reference these are all installed on my machine:

`libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3  gstreamer1.0-pulseaudio`

However after recompiling with the new source, I get the following error:

![Screenshot from 2022-02-04 11-26-38](https://user-images.githubusercontent.com/96459683/152582351-bafe8ccd-99c2-4e71-b778-922fb5dc6c7b.png)

My guess is that it still has an issue with how many files are opened through a stream I suppose. In the case of the android compilation, the issue is no longer present at all?

In this compilation, it works, for a while, sounds are played but after a few turns the entire application crashes.

I will update if I find anything.

**Comment by Robosturm** [comment]
Yes android works fine now.

But the error log sounds like Qt isn't freeing the resources on destruction....
So even though the pipe and file gets deleted on my end some data remains in the gstreamer lib as allocated.

Only idea i have currently is trying to build it against Qt 6.2.3 or Qt 6.3 or reporting it on qt's jira.
According to the Qt 6.2.3 release page the following things have been fixed:
QTBUG-96202 SoundEffect does not work in Qt6.2 beta3 in Windows and
Linux 
QTBUG-97758 QAudioOutput::setDevice doesn't work in Linux

**Comment by lonewolf19991** [comment]
I will build using 6.2.3 and report back with what I find.

**Comment by Robosturm** [comment]
From my point during most things 10 sounds are loaded at the same time at max.
And that's the minimum i can do with the on-Demand-Implementation
under coreengine/sounds/ondemandsound.cpp the game only loads sounds which should be played right now and deletes them once the replay ended.

**Comment by Robosturm** [comment]
The only other solution would be adding a compile option without sfx.....

**Comment by lonewolf19991** [comment]
if 6.2.3 does not solve it, I can try working on it for the linux compilation eventually, other than that, could be possible to try and use SDL's sound mixer in my linux compilation as it should not create a conflict with oxygine, SDL is used as a base for it.

**Comment by lonewolf19991** [comment]
I compiled with QT 6.2.3, the warnings of the previous screenshots do not show up anymore; the issue is tentatively solved, but will use it more and report any issues that arise from it.

**Comment by lonewolf19991** [comment]
I double checked, I played several matches and checked the console, no warnings or errors, so the issue is solved by upgrading to 6.2.3.
